name: buildAndTest
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run lint
        run: npm run lint

 # deployment:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout main branch
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Test application
  #       run: npm test

  #     - name: Build application
  #       run: npm run build

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.DIGITAL_ACCESS_TOKEN }},GITHUB_SHA
          script: |
           git pull origin develop

