name: deployment
on:
  push:
    branches: [ master]
  workflow_dispatch:
jobs:
  deployment:
    uses: ./.github/workflows/buildAndTest.yml
    runs-on: self-hosted
    steps:
      - name: Restard server
        run: pm2 restart tuneBudyServer

